In [1]:
import numpy as np

def multi(m,vp):
    c1=len(m[0])
    f2=len(vp)
    if c1!=f2:
        print("las matrices no se pueden multiplicar")
    else:
        f1=len(m)
        c2=len(vp[0])
        r=np.zeros(shape=(f1,c2))

        for i in range(f1):
            for j in range(c2):
                for k in range(c1):
                    r[i][j]+=m[i][k]*vp[k][j]
        return r

In [3]:
a = np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])

b = np.transpose(np.array([[5,-2,-3]]))

multi(a,b)

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

In [5]:
c = np.array([[0,-1,-1,3],[5,-5,-2,2],[1,0,4,5]])

d = np.array([[0,-3],[-2,-1],[3,-3]])
multi(c,d)

las matrices no se pueden multiplicar


In [6]:
e = np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,-4],[5,4,1,-5]])
f = np.array([[0,4,-7, 1, -6],[-1,-6,-5,1,1],[2, -1, -6, 5, -5],[-3,-6,6,3,5]])
multi(e,f)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

In [11]:
#La multiplicacion matricial no es conmutativa
g = np.array([[0,-3,4],[-2,-1,6],[3,-3,1]])
h = np.array([[2,4,0],[-2,-7,5],[6,8,8]])

multi(g,h)


array([[30., 53., 17.],
       [34., 47., 43.],
       [18., 41., -7.]])

In [12]:
multi(h,g)

array([[ -8., -10.,  32.],
       [ 29.,  -2., -45.],
       [  8., -50.,  80.]])