In [96]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
import numpy as np
import matplotlib.pyplot as plt


G = np.array([lambda x,y,z: 6*x - 2*np.cos(y*z) - 1.,
     lambda x,y,z: 9*y + np.sqrt( x**2 + np.sin(z) + 1.06 ) + 0.9,
     lambda x,y,z: 60*z + 3*np.exp(-x*y)+10*np.pi - 3])
#r=np.array([0.,0.,0.]
#vector evaluado en un punto inicial calcula F(Xn-1)
def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1],r[2])
        
    return v


In [105]:
GetF(G,np.array([0.,0.,0.]))

array([-3.        ,  1.92956301, 31.41592654])

In [101]:
def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2])  )/(2*h)
            
    
    return J


In [ ]:
GetJacobianbian()

In [109]:
def NewtonRaphson(G,r,itmax=1000,error=1e-9):
    
    it = 0
    d = 1.
    dvector = []
    
    while d > error and it < itmax:
        
        # Vector actual
        rc = r
        
        F = GetF(G,rc)
        J = GetJacobian(G,rc)
        InvJ = np.linalg.inv(J)
        
        r = rc - np.dot(InvJ,F)
        
        diff = r - rc
        
        d = np.max( np.abs(diff) )
        
        dvector.append(d)
        print(dvector)
        
        it += 1
    
    print(it)
    return r,dvector

In [110]:
r,dvector = NewtonRaphson(G,np.array([0.,0.,0.]))

[0.5235987756181211]
[0.5235987756181211, 0.013464494608999344]
[0.5235987756181211, 0.013464494608999344, 1.3125552370152338e-05]
[0.5235987756181211, 0.013464494608999344, 1.3125552370152338e-05, 7.48751061152575e-12]
4


In [36]:
r

array([ 0.49814468, -0.1996059 , -0.52882598])

In [56]:
G = np.array([lambda x,y: np.log(x**2 + y**2) - np.sin(x*y)-np.log(2)-np.log(np.pi),
     lambda x,y: np.exp(x-y) + np.cos(x*y)])


In [161]:
def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1])
        
    return v

def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1]) - f[i](rb[0],rb[1]))/(2*h)
            
    
    return J

def NewtonRaphson(G,r,itmax=1000,error=1e-9):
    
    it = 0
    d = 1.
    dvector = []
    
    while d > error and it < itmax:
        
        # Vector actual
        rc = r
        
        F = GetF(G,rc)
        J = GetJacobian(G,rc)
        InvJ = np.linalg.inv(J)
        
        r = rc - np.matmul(InvJ,F)
        
        diff = r - rc
        
        d = np.max( np.abs(diff) )
        
        dvector.append(d)
        print(dvector)
        
        it += 1
    
    print(it)
    return r,dvector

In [162]:
r,dvector = NewtonRaphson(G,np.array([2.,2.]))

[0.5210944589277715]
[0.5210944589277715, 0.23011830231874875]
[0.5210944589277715, 0.23011830231874875, 0.05938786252744843]
[0.5210944589277715, 0.23011830231874875, 0.05938786252744843, 0.004026892593212761]
[0.5210944589277715, 0.23011830231874875, 0.05938786252744843, 0.004026892593212761, 1.525217710929283e-05]
[0.5210944589277715, 0.23011830231874875, 0.05938786252744843, 0.004026892593212761, 1.525217710929283e-05, 2.1676838102280271e-10]
6


In [163]:
r

array([1.77245385, 1.77245385])

In [ ]:
# Descenso del gradiente

In [128]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time



In [177]:
G = np.array([lambda x,y,z: 6*x - 2*np.cos(y*z) - 1.,
     lambda x,y,z: 9*y + np.sqrt( x**2 + np.sin(z) + 1.06 ) + 0.9,
     lambda x,y,z: 60*z + 3*np.exp(-x*y)+10*np.pi - 3])


def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1],r[2])
        
    return v

def Metric(G,r):
    return 0.5*np.linalg.norm(GetF(G,r))**2


def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = (f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2]))/(2*h)
            
    
    return J
def Minimizer(G,r,lr=1e-2,epochs=int(1e4),error=1e-7):
    
    metric = 1
    it = 0
    
    M = np.array([])
    R = np.array([r])
    
    while metric > error and it < epochs:
        
        M = np.append(M,Metric(G,r))
        
        J = GetJacobian(G,r)
        Vector = GetF(G,r)
        
        # Machine learning
        r -= lr*np.dot(J,Vector)
        
        R = np.vstack((R,r))
        
        metric = Metric(G,r)
        
        it += 1
        
        if it%50 == 0:
            print(r)
    
    return r
xsol = Minimizer(G1,np.array([0.,0.,0.]))

<ipython-input-119-e31be8554ed3>:11: RuntimeWarning: overflow encountered in exp
  lambda x,y,z: 60*z + 3*np.exp(-x*y)+10*np.pi - 3])
<ipython-input-177-f27319aaaffb>:36: RuntimeWarning: invalid value encountered in double_scalars
  J[i,j] = (f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2]))/(2*h)


In [170]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
import matplotlib.animation as animation
from tqdm import tqdm

In [195]:
import numpy as np

def f2(x,y):
    return np.array([np.log(x**2 + y**2) - np.sin(x*y) - np.log(2) - np.log(np.pi),
                     np.exp(x-y) + np.cos(x*y)])

x0, y0 = 0.5, 0.1

Dx = lambda f,x,y, h=1e-5: (f(x+h,y) - f(x-h,y)) / (2*h)
Dy = lambda f,x,y, h=1e-5: (f(x,y+h) - f(x,y-h)) / (2*h)

Gradiente = lambda f,x,y: np.array([Dx(f,x,y), Dy(f,x,y)])
sol = Gradiente(f2,x0,y0)
sol

array([[ 3.74627882,  1.48682678],
       [ 0.26985564, -1.51681428]])

In [167]:
def Minimizer(f, N = 100, gamma = 0.01):
    
    r = np.zeros((N,2))
    r[0] = np.random.uniform(-5.,5.,size=2)
    
    Grad = np.zeros((N,2))
    Grad[0] = Gradient(f,r[0,0],r[0,1])
    
    # We save the gradient in each step

    for i in tqdm(range(1,N)):
        r[i] = r[i-1] - gamma*Gradient(f,r[i-1,0],r[i-1,1])
        Grad[i] = Gradient(f,r[i-1,0],r[i-1,1])
        
        
    return r,Grad
N = 200
r,Grad = Minimizer(f2,N)

100%|██████████| 199/199 [00:00<00:00, 13522.78it/s]


In [ ]:

#ln(x^2+y^2)-sen(xy)=ln(2)+ln(pi)
#e^(x-y)+cos(xy)=0